# Generated by Django 5.0.6 on 2024-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kdif',
            fields=[
                ('clave_grupo', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=5, primary_key=True, serialize=False)),
                ('descripcion_grupo', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=30, null=True)),
                ('campo_informativo', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C3', max_length=16, null=True)),
                ('almacen_default', models.DecimalField(blank=True, db_column='C4', decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'KDIF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kdig',
            fields=[
                ('clave_linea', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=5, primary_key=True, serialize=False)),
                ('descripcion_linea', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=30, null=True)),
                ('almacen_default', models.DecimalField(blank=True, db_column='C4', decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'KDIG',
                'managed': False,
            },
        ),
    ]
