# Generated by Django 5.0.6 on 2024-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_kdif_kdig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kdcorpo',
            fields=[
                ('clave_corporativo', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=7, primary_key=True, serialize=False)),
                ('descripcion_corporativo', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=80, null=True)),
                ('tipo_grupo', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C3', max_length=2, null=True)),
            ],
            options={
                'db_table': 'KDCORPO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kdpord',
            fields=[
                ('order_trabajo', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=10, primary_key=True, serialize=False)),
                ('estatus', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=1, null=True)),
                ('producto', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C3', max_length=18, null=True)),
                ('c4', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C4', max_length=1, null=True)),
                ('fecha_compromiso', models.DateTimeField(blank=True, db_column='C6', null=True)),
                ('hora_compromiso', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C7', max_length=5, null=True)),
                ('nivel_ingenieria_orden', models.DecimalField(blank=True, db_column='C8', decimal_places=0, max_digits=2, null=True)),
                ('cantidad_unidades', models.FloatField(blank=True, db_column='C9', null=True)),
                ('unidad', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C10', max_length=3, null=True)),
                ('factor', models.DecimalField(blank=True, db_column='C11', decimal_places=0, max_digits=15, null=True)),
                ('entrega_sugerida', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C12', max_length=1, null=True)),
                ('cantidad_acumulada', models.FloatField(blank=True, db_column='C13', null=True)),
                ('fecha_inicial', models.DateTimeField(blank=True, db_column='C14', null=True)),
                ('hora_inicial', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C15', max_length=5, null=True)),
                ('fecha_final', models.DateTimeField(blank=True, db_column='C16', null=True)),
                ('hora_final', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C17', max_length=5, null=True)),
                ('sucursal_de_orden', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C19', max_length=7, null=True)),
                ('genero_de_orden', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C20', max_length=1, null=True)),
                ('naturaleza', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C21', max_length=1, null=True)),
                ('grupo', models.DecimalField(blank=True, db_column='C22', decimal_places=0, max_digits=2, null=True)),
                ('tipo', models.DecimalField(blank=True, db_column='C23', decimal_places=0, max_digits=2, null=True)),
                ('folio_orden', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C24', max_length=7, null=True)),
                ('partida', models.DecimalField(blank=True, db_column='C25', decimal_places=0, max_digits=3, null=True)),
                ('consecutivo', models.DecimalField(blank=True, db_column='C26', decimal_places=0, max_digits=3, null=True)),
                ('talla', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C28', max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C29', max_length=10, null=True)),
                ('color', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C30', max_length=10, null=True)),
                ('campo_tmc_4', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C31', max_length=1, null=True)),
                ('campo_tmc_5', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C32', max_length=1, null=True)),
                ('ruta_a_seguir', models.DecimalField(blank=True, db_column='C33', decimal_places=0, max_digits=2, null=True)),
                ('referencia', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C35', max_length=30, null=True)),
            ],
            options={
                'db_table': 'KDPORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kdregiones',
            fields=[
                ('clave_region', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=3, primary_key=True, serialize=False)),
                ('descripcion_region', models.CharField(blank=True, db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=30, null=True)),
            ],
            options={
                'db_table': 'KDREGIONES',
                'managed': False,
            },
        ),
    ]
