# Generated by Django 5.0.6 on 2024-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_kdcorpo_kdpord_kdregiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kdvpresxsuc',
            fields=[
                ('clave_sucursal', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C1', max_length=7, primary_key=True, serialize=False)),
                ('moneda', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C2', max_length=7)),
                ('year', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C3', max_length=4)),
                ('zona', models.CharField(db_collation='Traditional_Spanish_CI_AS', db_column='C4', max_length=7)),
                ('presupuesto_ventas1', models.DecimalField(blank=True, db_column='C5', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas2', models.DecimalField(blank=True, db_column='C6', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas3', models.DecimalField(blank=True, db_column='C7', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas4', models.DecimalField(blank=True, db_column='C8', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas5', models.DecimalField(blank=True, db_column='C9', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas6', models.DecimalField(blank=True, db_column='C10', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas7', models.DecimalField(blank=True, db_column='C11', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas8', models.DecimalField(blank=True, db_column='C12', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas9', models.DecimalField(blank=True, db_column='C13', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas10', models.DecimalField(blank=True, db_column='C14', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas11', models.DecimalField(blank=True, db_column='C15', decimal_places=2, max_digits=15, null=True)),
                ('presupuesto_ventas12', models.DecimalField(blank=True, db_column='C16', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'KDVPRESXSUC',
                'managed': False,
            },
        ),
    ]
